/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeoplePeopleIdRouteImport } from './routes/people.$peopleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePeopleIdRoute = PeoplePeopleIdRouteImport.update({
  id: '/people/$peopleId',
  path: '/people/$peopleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people/$peopleId': typeof PeoplePeopleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/people/$peopleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/people/$peopleId'
  id: '__root__' | '/' | '/people/$peopleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeoplePeopleIdRoute: typeof PeoplePeopleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$peopleId': {
      id: '/people/$peopleId'
      path: '/people/$peopleId'
      fullPath: '/people/$peopleId'
      preLoaderRoute: typeof PeoplePeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeoplePeopleIdRoute: PeoplePeopleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
